apiVersion: v1
kind: Secret
metadata:
  name: kafka-client-config
  namespace: confluent-new
type: Opaque
data:
  kafka.properties: Ym9vdHN0cmFwLnNlcnZlcnM9a2Fma2EuY29uZmx1ZW50LW5ldy5zdmMuY2x1c3Rlci5sb2NhbDo5MDcxCnNlY3VyaXR5LnByb3RvY29sPVBMQUlOVEVYVA==
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elastic
  namespace: confluent-new
spec:
  serviceName: elastic
  podManagementPolicy: Parallel
  replicas: 3
  selector:
    matchLabels:
      app: elastic
  template:
    metadata:
      labels:
        app: elastic
    spec:
      nodeSelector:
        kubernetes.io/hostname: aks-default-35654945-vmss000002
      containers:
      - name: elastic
        image: confluentinc/cp-kafka:latest
        command:
        - /bin/sh
        - -c
        - |
          kafka-producer-perf-test \
            --topic ${HOSTNAME}  \
            --record-size 64 \
            --throughput 1 \
            --producer.config /mnt/kafka.properties \
            --num-records 230400
        volumeMounts:
        - name: kafka-properties
          mountPath: /mnt
          readOnly: true
        resources:
          requests:
            memory: 256Mi
            cpu: 250m
      volumes:
      - name: kafka-properties
        secret:
          secretName: kafka-client-config
---
apiVersion: v1
kind: Service
metadata:
  name: elastic
  namespace: confluent-new
spec:
  clusterIP: None
---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: elastic-0
  namespace: confluent-new
spec:
  replicas: 1
  partitionCount: 1
  configs:
    cleanup.policy: "delete"